security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        mongo_provider:
            mongodb:
                class: App\Document\User
                property: discordId
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Security\DiscordAuthenticator

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
