name: PHP CI
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

    - name: ⬇️ Checkout
      uses: actions/checkout@v2

    - name: 🔧 Setup PHP 8.0 with tools
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: composer
        coverage: xdebug

    - name: 📦 Cache Composer packages
      uses: actions/cache@v2
      id: composer-cache
      env:
        cache-name: cache-composer-packages
      with:
        path: ./vendor/
        key: ${{ runner.os }}-build-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-composer-

    - name: 📦 Cache Node modules
      uses: actions/cache@v2
      id: node-cache
      env:
        cache-name: cache-node-modules
      with:
        path: ./node_modules/
        key: ${{ runner.os }}-build-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-node-

    - name: ➕ Install Composer packages
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: cp ./.env.example ./.env && composer install

    - name: ➕ Install Node modules
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: yarn

    - name: 👷 Run production build
      run: yarn build

    - name: ✅ Run PHPUnit
      run: php bin/phpunit --coverage-clover build/coverage-report

    - name: 🤖 Publish code coverage
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
